### ISSUE TITLE
Readme missing infos

### ISSUE THREAD

**Issue by richardjuan** [numenta/nupic.nlp-examples#13]
hi, 
i'm trying to run the  "./run_association_experiment.py resources/animals.txt resources/vegetables.txt -p 100 -t 1000" following the readme, there was no mention of nupic.research that needed to be installed.

now that i did install them, i got the error saying that nltk is missing "simplify" module.
i found nothing on the internet on how to install them.

btw: no mention python tk that was needed to in order to install stuff from nltk

thanks in advance for helping me using your nupic example

**Comment by rhyolight** [comment]
I haven't run anything in this repo in over 10 months. I think it has been broken since Cortical.IO changed their API. Does that sound right, @subutai?

**Comment by subutai** [comment]
Yeah, I think it needs to be updated to reflect the cortical.io API changes.

**Comment by rhyolight** [comment]
I'm going to see if anyone in the community is interested in doing this.

**Comment by rhyolight** [comment]
@richardjuan See #14.
